remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: PaloR's notes
description: This page is a simple notes repository about different IT stuff
